name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Unit Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
          npx nx affected -t lint
          npx nx affected -t test --ci --code-coverage 
          npx nx affected -t build
          npx nx affected -t e2e
          npx nx affected -t test-storybook
