name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Unit Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
          npx nx affected -t lint --base=main --head=HEAD
          npx nx affected -t test --ci --code-coverage  --base=main --head=HEAD
          npx nx affected -t build --base=main --head=HEAD
          npx nx affected -t e2e --base=main --head=HEAD
          npx nx affected -t test-storybook --base=main --head=HEAD
