name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Unit Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
            npx nx affected --target=lint --parallel=3
            npx nx affected --target=test --parallel=3 --ci --code-coverage
            npx nx affected --target=build --parallel=3
