name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Unit Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
          npx nx affected:lint
          npx nx affected:test --ci --code-coverage
          npx nx affected:build
          npx nx affected:e2e 
          npx nx affected:test-storybook
